In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [68]:
house_data=pd.read_csv('train.csv')
house_data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [69]:
print(house_data.isna().sum())

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64


In [70]:
house_data['PoolQC'].isna().sum()

1453

In [71]:
house_data['SalePrice'].isna().sum()

0

In [72]:
cols=house_data.columns

In [73]:
cols

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [74]:
house_data['Id'].dtype

dtype('int64')

In [75]:
print('here',house_data['SalePrice'].dtype)

here int64


In [76]:
house_data.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...   
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [77]:
house_data['YrSold'].dtype

dtype('int64')

In [78]:
s=house_data['MoSold'].value_counts()
s.index[0],s

(6,
 6     253
 7     234
 5     204
 4     141
 8     122
 3     106
 10     89
 11     79
 9      63
 12     59
 1      58
 2      52
 Name: MoSold, dtype: int64)

In [79]:
cat_features=[]
for col in cols:
    if house_data[col].isna().sum()!=0:
        if house_data[col].dtype=='object':
            house_data[col].fillna('missing',inplace=True)
            cat_features.append(col)
        elif house_data[col].dtype=='int64':
            s=house_data[col].value_counts()
            house_data[col].fillnana(s.index[0],inplace=True)
            #cat_features.append(col)
        else:
            house_data[col].fillna(house_data[col].mean(),inplace=True)
    else:
        if house_data[col].dtype=='object':
            cat_features.append(col)
            
            

In [80]:
house_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street    Alley  \
0        1          60       RL         65.0     8450   Pave  missing   
1        2          20       RL         80.0     9600   Pave  missing   
2        3          60       RL         68.0    11250   Pave  missing   
3        4          70       RL         60.0     9550   Pave  missing   
4        5          60       RL         84.0    14260   Pave  missing   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave  missing   
1456  1457          20       RL         85.0    13175   Pave  missing   
1457  1458          70       RL         66.0     9042   Pave  missing   
1458  1459          20       RL         68.0     9717   Pave  missing   
1459  1460          20       RL         75.0     9937   Pave  missing   

     LotShape LandContour Utilities  ... PoolArea   PoolQC    Fence  \
0         Reg         Lvl    AllPub  ...        0  missing  missing   
1         Reg         Lvl    AllPub  ...        0  missing  missing   
2         IR1         Lvl    AllPub  ...        0  missing  missing   
3         IR1         Lvl    AllPub  ...        0  missing  missing   
4         IR1         Lvl    AllPub  ...        0  missing  missing   
...       ...         ...       ...  ...      ...      ...      ...   
1455      Reg         Lvl    AllPub  ...        0  missing  missing   
1456      Reg         Lvl    AllPub  ...        0  missing    MnPrv   
1457      Reg         Lvl    AllPub  ...        0  missing    GdPrv   
1458      Reg         Lvl    AllPub  ...        0  missing  missing   
1459      Reg         Lvl    AllPub  ...        0  missing  missing   

     MiscFeature MiscVal MoSold YrSold  SaleType  SaleCondition  SalePrice  
0        missing       0      2   2008        WD         Normal     208500  
1        missing       0      5   2007        WD         Normal     181500  
2        missing       0      9   2008        WD         Normal     223500  
3        missing       0      2   2006        WD        Abnorml     140000  
4        missing       0     12   2008        WD         Normal     250000  
...          ...     ...    ...    ...       ...            ...        ...  
1455     missing       0      8   2007        WD         Normal     175000  
1456     missing       0      2   2010        WD         Normal     210000  
1457        Shed    2500      5   2010        WD         Normal     266500  
1458     missing       0      4   2010        WD         Normal     142125  
1459     missing       0      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [81]:
house_data.isna().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [82]:
cols

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [83]:
cat_features

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [84]:
cat_features.remove('SalePrice')

ValueError: list.remove(x): x not in list

In [85]:
cat_features

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [86]:
X=house_data.drop('SalePrice',axis=1)
y=house_data['SalePrice']

In [87]:
#encoding

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot=OneHotEncoder(sparse=False)
transformer=ColumnTransformer([
    ('one_hot',one_hot,cat_features)
],
                             remainder='passthrough')

transformed_X=transformer.fit_transform(X)

In [88]:
transformed_X

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 2.000e+00,
        2.008e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 5.000e+00,
        2.007e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 9.000e+00,
        2.008e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.500e+03, 5.000e+00,
        2.010e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 4.000e+00,
        2.010e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 6.000e+00,
        2.008e+03]])

In [89]:
transformed_X.shape

(1460, 305)

In [90]:
X.shape

(1460, 80)

In [91]:
len(house_data)

1460

In [92]:
from sklearn.linear_model import Lasso

np.random.seed(42)

model=Lasso(max_iter=10000)
model.fit(transformed_X,y)

Lasso(max_iter=10000)

In [132]:
test_df=pd.read_csv('test.csv')
test_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [133]:
type(cols)

pandas.core.indexes.base.Index

In [134]:
for col in cols:
    if col!='SalePrice' and test_df[col].isna().sum()!=0:
        if test_df[col].dtype=='object':
            test_df[col].fillna('missing',inplace=True)
            #cat_features.append(col)
        elif test_df[col].dtype=='int64':
            s=test_df[col].value_counts()
            test_df[col].fillnana(s.index[0],inplace=True)
            #cat_features.append(col)
        else:
            test_df[col].fillna(test_df[col].mean(),inplace=True)
#     else:
#         if test_df[col].dtype=='object' or test_df[col].dtype=='int64':
#             cat_features.append(col)


In [135]:
test_df.isna().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 80, dtype: int64

In [136]:
transformed_test=transformer.fit_transform(test_df)

In [137]:
transformed_test

array([[0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 6.000e+00,
        2.010e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.250e+04, 6.000e+00,
        2.010e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 3.000e+00,
        2.010e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 9.000e+00,
        2.006e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 7.000e+02, 7.000e+00,
        2.006e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.100e+01,
        2.006e+03]])

In [138]:
transformed_X.shape

(1460, 305)

In [139]:
transformed_test.shape

(1459, 293)

In [140]:
transformed_test[0]

array([0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       1.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e

In [141]:
zer=np.zeros((len(transformed_test),1))
zer

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [142]:
final_train,final_test=transformed_X.align(transformed_test,join='inner',axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'align'

In [121]:

for i in range(transformed_X.shape[1]-transformed_test.shape[1]):
    transformed_test=np.append(transformed_test,zer,axis=1)

In [122]:
len(transformed_test[0])

305

In [123]:
transformed_test.shape

(1459, 305)

In [124]:
y_preds=model.predict(transformed_test)

In [125]:
y_preds

array([2.01062065e+08, 7.17997522e+07, 2.35590609e+08, ...,
       3.29657378e+08, 1.87675082e+08, 1.92901289e+08])

In [128]:
cols


Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [129]:
test_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [130]:
ans_df=pd.DataFrame({
    'Id':test_df['Id'],
    'SalePrice':y_preds
})
ans_df

Id     SalePrice
0     1461  2.010621e+08
1     1462  7.179975e+07
2     1463  2.355906e+08
3     1464  1.823433e+08
4     1465  1.113743e+08
...    ...           ...
1454  2915  8.128304e+07
1455  2916  8.081108e+07
1456  2917  3.296574e+08
1457  2918  1.876751e+08
1458  2919  1.929013e+08

[1459 rows x 2 columns]

In [131]:
ans_df.to_csv('sample_submission.csv',index=False)

In [148]:
X


Id  MSSubClass MSZoning  LotFrontage  LotArea Street    Alley  \
0        1          60       RL         65.0     8450   Pave  missing   
1        2          20       RL         80.0     9600   Pave  missing   
2        3          60       RL         68.0    11250   Pave  missing   
3        4          70       RL         60.0     9550   Pave  missing   
4        5          60       RL         84.0    14260   Pave  missing   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave  missing   
1456  1457          20       RL         85.0    13175   Pave  missing   
1457  1458          70       RL         66.0     9042   Pave  missing   
1458  1459          20       RL         68.0     9717   Pave  missing   
1459  1460          20       RL         75.0     9937   Pave  missing   

     LotShape LandContour Utilities  ... ScreenPorch PoolArea   PoolQC  \
0         Reg         Lvl    AllPub  ...           0        0  missing   
1         Reg         Lvl    AllPub  ...           0        0  missing   
2         IR1         Lvl    AllPub  ...           0        0  missing   
3         IR1         Lvl    AllPub  ...           0        0  missing   
4         IR1         Lvl    AllPub  ...           0        0  missing   
...       ...         ...       ...  ...         ...      ...      ...   
1455      Reg         Lvl    AllPub  ...           0        0  missing   
1456      Reg         Lvl    AllPub  ...           0        0  missing   
1457      Reg         Lvl    AllPub  ...           0        0  missing   
1458      Reg         Lvl    AllPub  ...           0        0  missing   
1459      Reg         Lvl    AllPub  ...           0        0  missing   

        Fence MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0     missing     missing       0      2    2008        WD         Normal  
1     missing     missing       0      5    2007        WD         Normal  
2     missing     missing       0      9    2008        WD         Normal  
3     missing     missing       0      2    2006        WD        Abnorml  
4     missing     missing       0     12    2008        WD         Normal  
...       ...         ...     ...    ...     ...       ...            ...  
1455  missing     missing       0      8    2007        WD         Normal  
1456    MnPrv     missing       0      2    2010        WD         Normal  
1457    GdPrv        Shed    2500      5    2010        WD         Normal  
1458  missing     missing       0      4    2010        WD         Normal  
1459  missing     missing       0      6    2008        WD         Normal  

[1460 rows x 80 columns]

In [149]:
train=pd.get_dummies(X)

In [150]:
train

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
0        1          60         65.0     8450            7            5   
1        2          20         80.0     9600            6            8   
2        3          60         68.0    11250            7            5   
3        4          70         60.0     9550            7            5   
4        5          60         84.0    14260            8            5   
...    ...         ...          ...      ...          ...          ...   
1455  1456          60         62.0     7917            6            5   
1456  1457          20         85.0    13175            6            6   
1457  1458          70         66.0     9042            7            9   
1458  1459          20         68.0     9717            5            6   
1459  1460          20         75.0     9937            5            6   

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  SaleType_ConLw  \
0          2003          2003       196.0         706  ...               0   
1          1976          1976         0.0         978  ...               0   
2          2001          2002       162.0         486  ...               0   
3          1915          1970         0.0         216  ...               0   
4          2000          2000       350.0         655  ...               0   
...         ...           ...         ...         ...  ...             ...   
1455       1999          2000         0.0           0  ...               0   
1456       1978          1988       119.0         790  ...               0   
1457       1941          2006         0.0         275  ...               0   
1458       1950          1996         0.0          49  ...               0   
1459       1965          1965         0.0         830  ...               0   

      SaleType_New  SaleType_Oth  SaleType_WD  SaleCondition_Abnorml  \
0                0             0            1                      0   
1                0             0            1                      0   
2                0             0            1                      0   
3                0             0            1                      1   
4                0             0            1                      0   
...            ...           ...          ...                    ...   
1455             0             0            1                      0   
1456             0             0            1                      0   
1457             0             0            1                      0   
1458             0             0            1                      0   
1459             0             0            1                      0   

      SaleCondition_AdjLand  SaleCondition_Alloca  SaleCondition_Family  \
0                         0                     0                     0   
1                         0                     0                     0   
2                         0                     0                     0   
3                         0                     0                     0   
4                         0                     0                     0   
...                     ...                   ...                   ...   
1455                      0                     0                     0   
1456                      0                     0                     0   
1457                      0                     0                     0   
1458                      0                     0                     0   
1459                      0                     0                     0   

      SaleCondition_Normal  SaleCondition_Partial  
0                        1                      0  
1                        1                      0  
2                        1                      0  
3                        0                      0  
4                        1                      0  
...                    ...                    ...  
1455                     1                      0  


In [151]:
test=pd.get_dummies(test_df)

In [152]:
final_train,final_test=train.align(test,join='inner',axis=1)

In [153]:
final_test.shape,final_train.shape

((1459, 286), (1460, 286))

In [163]:
np.random.seed(42)

model=Lasso(max_iter=100000,alpha=0.1)
model.fit(final_train,y)

Lasso(alpha=0.1, max_iter=100000)

In [164]:
y_preds=model.predict(final_test)

In [165]:
ans_df=pd.DataFrame({
    'Id':test_df['Id'],
    'SalePrice':y_preds
})
ans_df

Id      SalePrice
0     1461  109362.673436
1     1462  124847.594353
2     1463  180679.525635
3     1464  194174.887574
4     1465  209186.764623
...    ...            ...
1454  2915   82740.026758
1455  2916   81160.138542
1456  2917  174355.786704
1457  2918  114433.518515
1458  2919  225275.919445

[1459 rows x 2 columns]

In [166]:
ans_df.to_csv('sample_submission.csv',index=False)

In [191]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

model=RandomForestRegressor(n_estimators=200)
model.fit(final_train,y)

RandomForestRegressor(n_estimators=200)

In [192]:
y_preds=model.predict(final_test)

In [193]:
from sklearn.metrics import SCORERS

sorted(SCORERS.keys())

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_we

In [194]:
from sklearn.model_selection import cross_val_score

np.random.seed(42)

np.sqrt(-1*cross_val_score(model,final_train,y,scoring='neg_mean_squared_log_error'))

array([0.13909187, 0.15493939, 0.14438997, 0.1390466 , 0.15700289])

In [195]:
model

RandomForestRegressor(n_estimators=200)

In [196]:
y_preds=model.predict(final_test)

In [197]:
ans_df=pd.DataFrame({
    'Id':test_df['Id'],
    'SalePrice':y_preds
})
ans_df

Id   SalePrice
0     1461  129321.000
1     1462  154453.875
2     1463  180242.285
3     1464  182827.435
4     1465  198969.380
...    ...         ...
1454  2915   85148.750
1455  2916   85432.000
1456  2917  151689.510
1457  2918  114055.000
1458  2919  228697.710

[1459 rows x 2 columns]

In [198]:
ans_df.to_csv('sample_submission.csv',index=False)

In [188]:
# from sklearn.svm import SVR

# np.random.seed(42)

# model=SVR(kernel='rbf')
# model.fit(final_train,y)

SVR()

In [189]:
# np.random.seed(42)

# np.sqrt(-1*cross_val_score(model,final_train,y,scoring='neg_mean_squared_log_error'))

array([0.38844891, 0.42579563, 0.41064524, 0.38081456, 0.39226093])