In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [107]:
titanic_df=pd.read_csv('train.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [108]:
titanic_df.shape

(891, 12)

In [109]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [110]:
titanic_df['Age'].fillna(titanic_df['Age'].mean(),inplace=True)
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Cabin Embarked  
0        1      0         A/5 21171   7.2500   NaN        S  
1        1      0          PC 17599  71.2833   C85        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S  
3        1      0            113803  53.1000  C123        S  
4        0      0            373450   8.0500   NaN        S  
..     ...    ...               ...      ...   ...      ...  
886      0      0            211536  13.0000   NaN        S  
887      0      0            112053  30.0000   B42        S  
888      1      2        W./C. 6607  23.4500   NaN        S  
889      0      0            111369  30.0000  C148        C  
890      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [111]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [112]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [113]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [114]:
X=titanic_df.drop('Survived',axis=1)
y=titanic_df['Survived']


In [115]:
X.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [116]:
X.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [117]:
X.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [118]:
X.drop(['Name','Ticket','Cabin','Embarked'],axis=1,inplace=True)



In [119]:
X.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare
0            1       3    male  22.0      1      0   7.2500
1            2       1  female  38.0      1      0  71.2833
2            3       3  female  26.0      0      0   7.9250
3            4       1  female  35.0      1      0  53.1000
4            5       3    male  35.0      0      0   8.0500

In [120]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot=OneHotEncoder(sparse=False)
cat_features=['Sex']
transformer=ColumnTransformer([
                                ('one_hot',one_hot,cat_features)
                            ],
                             remainder='passthrough')
transformed_X=transformer.fit_transform(X)

In [121]:
transformed_X

array([[  0.    ,   1.    ,   1.    , ...,   1.    ,   0.    ,   7.25  ],
       [  1.    ,   0.    ,   2.    , ...,   1.    ,   0.    ,  71.2833],
       [  1.    ,   0.    ,   3.    , ...,   0.    ,   0.    ,   7.925 ],
       ...,
       [  1.    ,   0.    , 889.    , ...,   1.    ,   2.    ,  23.45  ],
       [  0.    ,   1.    , 890.    , ...,   0.    ,   0.    ,  30.    ],
       [  0.    ,   1.    , 891.    , ...,   0.    ,   0.    ,   7.75  ]])

In [122]:
transformed_X.shape

(891, 8)

In [123]:
transformed_X.shape[1]

8

In [124]:
print(transformed_X)

[[  0.       1.       1.     ...   1.       0.       7.25  ]
 [  1.       0.       2.     ...   1.       0.      71.2833]
 [  1.       0.       3.     ...   0.       0.       7.925 ]
 ...
 [  1.       0.     889.     ...   1.       2.      23.45  ]
 [  0.       1.     890.     ...   0.       0.      30.    ]
 [  0.       1.     891.     ...   0.       0.       7.75  ]]


In [125]:
transformed_X.shape

(891, 8)

In [126]:
transformed_X[:10]

array([[ 0.        ,  1.        ,  1.        ,  3.        , 22.        ,
         1.        ,  0.        ,  7.25      ],
       [ 1.        ,  0.        ,  2.        ,  1.        , 38.        ,
         1.        ,  0.        , 71.2833    ],
       [ 1.        ,  0.        ,  3.        ,  3.        , 26.        ,
         0.        ,  0.        ,  7.925     ],
       [ 1.        ,  0.        ,  4.        ,  1.        , 35.        ,
         1.        ,  0.        , 53.1       ],
       [ 0.        ,  1.        ,  5.        ,  3.        , 35.        ,
         0.        ,  0.        ,  8.05      ],
       [ 0.        ,  1.        ,  6.        ,  3.        , 29.69911765,
         0.        ,  0.        ,  8.4583    ],
       [ 0.        ,  1.        ,  7.        ,  1.        , 54.        ,
         0.        ,  0.        , 51.8625    ],
       [ 0.        ,  1.        ,  8.        ,  3.        ,  2.        ,
         3.        ,  1.        , 21.075     ],
       [ 1.        ,  0.        

In [127]:
print(transformed_X[:,0])

[0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0.
 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1.

In [128]:
titanic_df_trfd=pd.DataFrame(transformed_X)

In [129]:
titanic_df_trfd

0    1      2    3          4    5    6        7
0    0.0  1.0    1.0  3.0  22.000000  1.0  0.0   7.2500
1    1.0  0.0    2.0  1.0  38.000000  1.0  0.0  71.2833
2    1.0  0.0    3.0  3.0  26.000000  0.0  0.0   7.9250
3    1.0  0.0    4.0  1.0  35.000000  1.0  0.0  53.1000
4    0.0  1.0    5.0  3.0  35.000000  0.0  0.0   8.0500
..   ...  ...    ...  ...        ...  ...  ...      ...
886  0.0  1.0  887.0  2.0  27.000000  0.0  0.0  13.0000
887  1.0  0.0  888.0  1.0  19.000000  0.0  0.0  30.0000
888  1.0  0.0  889.0  3.0  29.699118  1.0  2.0  23.4500
889  0.0  1.0  890.0  1.0  26.000000  0.0  0.0  30.0000
890  0.0  1.0  891.0  3.0  32.000000  0.0  0.0   7.7500

[891 rows x 8 columns]

In [130]:
X

PassengerId  Pclass     Sex        Age  SibSp  Parch     Fare
0              1       3    male  22.000000      1      0   7.2500
1              2       1  female  38.000000      1      0  71.2833
2              3       3  female  26.000000      0      0   7.9250
3              4       1  female  35.000000      1      0  53.1000
4              5       3    male  35.000000      0      0   8.0500
..           ...     ...     ...        ...    ...    ...      ...
886          887       2    male  27.000000      0      0  13.0000
887          888       1  female  19.000000      0      0  30.0000
888          889       3  female  29.699118      1      2  23.4500
889          890       1    male  26.000000      0      0  30.0000
890          891       3    male  32.000000      0      0   7.7500

[891 rows x 7 columns]

In [131]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [132]:
np.random.seed(42)
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(transformed_X,y)

#clf.score(X_test,y_test)

RandomForestClassifier()

In [133]:
titanic_df_test=pd.read_csv('test.csv')
titanic_df_test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [134]:
titanic_df_test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [135]:
titanic_df_test['Age'].fillna(titanic_df_test['Age'].mean(),inplace=True)


In [136]:
titanic_df_test['Fare'].fillna(titanic_df_test['Fare'].mean(),inplace=True)

In [137]:
titanic_df_test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [138]:
titanic_df_test.drop(['Name','Ticket','Cabin','Embarked'],axis=1,inplace=True)

In [139]:
titanic_df_test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare
0          892       3    male  34.5      0      0   7.8292
1          893       3  female  47.0      1      0   7.0000
2          894       2    male  62.0      0      0   9.6875
3          895       3    male  27.0      0      0   8.6625
4          896       3  female  22.0      1      1  12.2875

In [140]:
transformed_X_tt=transformer.fit_transform(titanic_df_test)

In [141]:
transformed_X_tt

array([[0.00000e+00, 1.00000e+00, 8.92000e+02, ..., 0.00000e+00,
        0.00000e+00, 7.82920e+00],
       [1.00000e+00, 0.00000e+00, 8.93000e+02, ..., 1.00000e+00,
        0.00000e+00, 7.00000e+00],
       [0.00000e+00, 1.00000e+00, 8.94000e+02, ..., 0.00000e+00,
        0.00000e+00, 9.68750e+00],
       ...,
       [0.00000e+00, 1.00000e+00, 1.30700e+03, ..., 0.00000e+00,
        0.00000e+00, 7.25000e+00],
       [0.00000e+00, 1.00000e+00, 1.30800e+03, ..., 0.00000e+00,
        0.00000e+00, 8.05000e+00],
       [0.00000e+00, 1.00000e+00, 1.30900e+03, ..., 1.00000e+00,
        1.00000e+00, 2.23583e+01]])

In [142]:
transformed_X_tt.shape

(418, 8)

In [143]:
y_preds=clf.predict(transformed_X_tt)

In [144]:
y_preds

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [159]:
ans_df=pd.DataFrame({
    'PassengerId':titanic_df_test['PassengerId'],
    'Survived':y_preds
})

In [160]:
ans_df

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [176]:
ans_df.to_csv('gender_submission2.csv',index=False)

## USING SVC

In [172]:
from sklearn.svm import SVC
clf2=SVC(C=1.0)
#clf2.fit(transformed_X,y)

In [173]:
from sklearn.model_selection import cross_val_score

cross_val_score(clf2,transformed_X,y)

array([0.61452514, 0.63483146, 0.65168539, 0.64044944, 0.65730337])

In [175]:
clf2.fit(transformed_X,y)
y_preds_2=clf2.predict(transformed_X_tt)

In [177]:
ans_df_2=pd.DataFrame({
    'PassengerId':titanic_df_test['PassengerId'],
    'Survived':y_preds_2
})

In [178]:
ans_df_2.to_csv('gender_submission.csv',index=False)